---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.12.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: secretKey
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secret
      valuesKey: postgresqlPassword
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: authentik-secret
      valuesKey: postgresqlPassword
      targetPath: authentik.postgresql.password
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.10.7
      digest: "sha256:f019439323ae8ffb88771584641072ffb64079a895d8d15ee7ada2da210de2a1"
    replicas: 1
    worker:
      replicas: 1
    env:
      TZ: "${TIMEZONE}"
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.org/websocket-services: authentik
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
        # nginx.ingress.kubernetes.io/client-body-buffer-size: "32k"
        # nginx.ingress.kubernetes.io/client-header-buffer-size: "32k"
        # nginx.ingress.kubernetes.io/large-client-header-buffers: "4 32k"
        # nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
        # nginx.ingress.kubernetes.io/server-snippet: |
        #   client_header_buffer_size 32k;
        #   large_client_header_buffers 4 32k;
        hajimari.io/icon: mdi:account-lock
        hajimari.io/enable: "true"
      hosts:
        - host: &host auth.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    prometheus:
      serviceMonitor:
        create: true
    authentik:
      log_level: debug
      postgresql:
        name: "authentik"
        user: "authentik"
      email:
        from: "authentik@${SECRET_DOMAIN}"
        username: "${SECRET_AWS_SMTP_USERNAME}"
        password: "${SECRET_AWS_SMTP_PASSWORD}"
        host: email-smtp.us-east-1.amazonaws.com
        port: 587
        use_tls: true
      error_reporting:
        enabled: false
        send_pii: false
    postgresql:
      enabled: true
      postgresqlMaxConnections: 500
      postgresqlUsername: "authentik"
      postgresqlDatabase: "authentik"
    redis:
      enabled: true
      architecture: standalone
