---
name: "Lychee"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  WORKFLOW_ISSUE_NUMBER: 1061
  ISSUE_LABEL: lint/lychee

jobs:
  lychee:
    name: Lychee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Scan for broken links
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2
        with:
          args: --verbose --no-progress --exclude-mail './**/*.md'
          output: /tmp/results.md
          labels: "${{ env.ISSUE_LABEL }}"

      - name: Update Issue
        uses: peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94 # v5
        with:
          title: Link Checker Dashboard 🔗
          issue-number: "${{ env.WORKFLOW_ISSUE_NUMBER }}"
          content-filepath: /tmp/results.md
          labels: "${{ env.ISSUE_LABEL }}"
